# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.FileField(blank=True, help_text='', upload_to='images/posts'),
        ),
    ]
