# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_post_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='text',
        ),
    ]
