# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(help_text='', max_length=60, primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='', max_length=60)),
            ],
        ),
    ]
