# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20161030_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, help_text='', upload_to='profile-pics'),
        ),
    ]
